'use client';

import { useEffect, useState } from 'react';
import { Check, X, KeyRound } from 'lucide-react';
import { registerMockUser } from '@/lib/mockAuth';
import { generateEmployeeId, initialEmployees, initialPendingRegistrations, readMockCollection, writeMockCollection } from '@/lib/mockData';

export default function PendingRegistrationsPage() {
  const [pending, setPending] = useState(initialPendingRegistrations);
  const [employees, setEmployees] = useState(initialEmployees);
  const [message, setMessage] = useState('');
  useEffect(() => { const load = () => { setPending(readMockCollection('pending-registrations', initialPendingRegistrations)); setEmployees(readMockCollection('employees', initialEmployees)); }; const timeoutId = window.setTimeout(load, 0); return () => window.clearTimeout(timeoutId); }, []);
  const updateRequest = (request, approved) => { const nextPending = pending.filter((item) => item.id !== request.id); setPending(nextPending); writeMockCollection('pending-registrations', nextPending); if (!approved) { setMessage(`${request.fullName}'s request was rejected.`); return; } const id = generateEmployeeId(request.fullName, request.joiningYear, employees); const employee = { id, name: request.fullName, email: request.email, phone: request.phone, companyName: request.companyName, dept: request.dept, role: request.role, status: 'Active', joiningYear: request.joiningYear }; const nextEmployees = [...employees, employee]; setEmployees(nextEmployees); writeMockCollection('employees', nextEmployees); registerMockUser({ fullName: request.fullName, email: request.email, password: request.password || `Dayflow@${request.joiningYear}`, role: 'employee', phone: request.phone, companyName: request.companyName, joiningYear: request.joiningYear, loginId: id }); setMessage(`${request.fullName} approved. Login ID: ${id}. Temporary password: ${request.password ? 'the password supplied at registration' : `Dayflow@${request.joiningYear}`}`); };
  return <div className="space-y-6"><div><h2 className="text-xl font-bold text-gray-900">Registration Requests</h2><p className="mt-0.5 text-xs text-gray-500">Approve employees and generate their credentials.</p></div>{message && <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-xs font-medium text-emerald-700"><KeyRound className="mr-2 inline-block h-4 w-4" />{message}</div>}<div className="grid gap-4">{pending.length === 0 ? <div className="rounded-2xl bg-white p-8 text-center text-sm text-gray-500">No pending registration requests.</div> : pending.map((request) => <div key={request.id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold text-gray-900">{request.fullName}</h3><p className="text-xs text-gray-500">{request.role} · {request.dept}</p><p className="mt-1 text-xs text-gray-400">{request.email} · Joining year {request.joiningYear}</p></div><div className="flex gap-2"><button onClick={() => updateRequest(request, true)} className="flex items-center gap-1 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700"><Check className="h-4 w-4" /> Approve</button><button onClick={() => updateRequest(request, false)} className="flex items-center gap-1 rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-700"><X className="h-4 w-4" /> Reject</button></div></div></div>)}</div></div>;
}
